Transaction reduce relay feature.
ripple/rippled pull request #3618
Opened 2020-09-28 23:00 UTC by gregtatcam

## High Level Overview of Change

A node randomly selects peers to relay a transaction to.
It aggregates and sends once a second to all peers
transactions' hashes, which have not been sent. Peers
then request missing transactions from the node.

### Context of Change

This is a new feature. The architecture is based on a data 
modeling analysis of the crawled XRPL network. The analysis 
shows a densely connected core with the rest of the nodes
having multiple connections to the nodes in the core. Random
selection of peers and periodic pull of missing transactions
reduces redundancy in the transaction's propagation.

### Type of Change

- [x ] New feature (non-breaking change which adds functionality)

2020-10-16 00:58 UTC, pwang200 reviewed
Overall looks good.

The code is difficult to unit test. I wonder what cases were tested in a network.

2020-10-16 00:58 UTC, pwang200 commented on src/ripple/overlay/impl/OverlayImpl.cpp
> +        toSelect = (toSelect > exclude) ? (toSelect - exclude) : 0;
Could you please explain the calculation of `toSelect`? I think the part that confused me is the definition of `TX_RELAY_TO_PEERS`, i.e. "Percentage of peers to select from total peers" as in config.h. My understanding is that if a node has 100 peers and `TX_RELAY_TO_PEERS`=50, then the node wants to make sure 50 of its peers have the Tx. Either they have the Tx already or the node will forward the Tx to them. 

Now consider a case that `toSkip.size()` = 40 and `notEnabled` = 0. Then `exclude` = 40, `peers.size()` = 60, and `TX_RELAY_TO_PEERS * peers.size() / 100` = 50*60/100 = 30. And 30 < 40, so `toSelect` will be 0. So no forwarding now. Hope my calculation is correct.

2020-10-26 18:50 UTC, pwang200 commented on src/ripple/proto/ripple.proto
> +    repeated bytes hash = 1;
yeah.

2020-11-15 11:02 UTC, nbougalis requested changes

2020-12-01 22:44 UTC, pwang200 reviewed
I added several more comments and a placeholder for resuming the review once the handshake PR is merged.

2020-12-02 22:15 UTC, gregtatcam commented on src/ripple/overlay/impl/PeerImp.cpp
>              }
will update.

2020-12-03 14:24 UTC, gregtatcam commented on src/ripple/overlay/impl/OverlayImpl.cpp
> +        app_.config().TX_RELAY_PERCENTAGE * (active - disabled) / 100);
actually more like this: `toRelay = min + disabled + pct * (active - min - disabled) ` assuming `active > min + disabled`. we don't want to include `disabled` in the random sample to relay.

2020-12-08 16:22 UTC, nbougalis commented on src/ripple/overlay/impl/OverlayImpl.cpp
> +        app_.config().TX_RELAY_PERCENTAGE * (active - disabled) / 100);
Can we simply have a "target" value and simply reduce gradually? Something like: `(current - target) / 4`?

2020-12-08 16:34 UTC, nbougalis commented on src/ripple/overlay/impl/PeerImp.h
> +    hash_set<uint256> txQueue_;
:+1:

2020-12-26 20:41 UTC, nbougalis approved these changes

2021-01-05 00:07 UTC, nbougalis commented
@gregtatcam can you rebase this on the latest tip of **develop** please?

2021-01-13 23:51 UTC, pwang200 approved these changes
:+1: Looks good!

2021-03-17 19:45 UTC, pwang200 approved these changes
:+1: LGTM

2021-03-17 22:11 UTC, troylougheed commented
Unsubscribe￼

2021-09-14 16:30 UTC, closed without merging