[TRIVIAL] Add instructions to use 64-bit Windows build tools
ripple/rippled pull request #3725
Opened 2021-01-14 21:31 UTC by ximinez

## High Level Overview of Change

I finally, accidentally figured out why my Windows command line builds (using msbuild) will fail every once in a while to link because a file memory mapping fails, or a plain old out of memory. By default, the 32-bit versions of these tools are used, so the system has ample memory available, the process does not. This change adds instructions to use the `CMAKE_GENERATOR_TOOLSET` to use the 64-bit versions of the tools. The [cmake docs](https://cmake.org/cmake/help/latest/variable/CMAKE_GENERATOR_TOOLSET.html) are clear that "The value of this variable should never be modified by project code.".

Note that this has never happened to me in the IDE, presumably because the default settings use the 64-bit tools.

I also updated Travis to use this option, though I'll only know if it works when that finishes. I'll remove the second commit if not.

### Type of Change

- [X ] Documentation Updates

## Test Plan

No code changes to test. If CI works, it works, and the other change is to documentation.

2021-01-15 22:49 UTC, nbougalis approved these changes

2021-01-15 22:50 UTC, nbougalis requested changes
Seems to fail CI with an error.

2021-01-20 19:07 UTC, ximinez commented
@nbougalis CI issue fixed.

2021-01-21 19:00 UTC, nbougalis approved these changes

2021-01-21 19:01 UTC, nbougalis commented
Looks good. We should get a signoff from @miguelportilla or someone else with Windows though, just in case. If we can do that, this should get into **b12**, @manojsdoshi.

2021-01-21 19:11 UTC, ximinez commented
Rebased on to 1.7.0-b11, and squashed the two Travis-only commits into one. The commits will all be squashed to one once I get final approval.

2021-01-22 21:27 UTC, miguelportilla approved these changes
👍

2021-01-22 22:21 UTC, ximinez commented
Squashed and rewrote the commit message.

2021-01-27 00:48 UTC, closed without merging