Support boost 1.76:
ripple/rippled pull request #3819
Opened 2021-04-11 21:33 UTC by seelabs

* remove unused `std::hash` specialization
* Use `std::chrono::floor` instead of `floor`

This patch was tested against boost 1.76-rc1. We should wait to merge it until boost 1.76 is officially released.

2021-04-12 16:07 UTC, HowardHinnant commented
Waiting for release of 1.76 to test.

2021-04-19 20:05 UTC, HowardHinnant requested changes
Looks good, but needs a `#include <vector>` here: src/test/unit_test/multi_runner.cpp

2021-04-20 01:16 UTC, seelabs commented
Thanks @HowardHinnant. Added missing include in the patch `c1c5fb24ea Add missing include`

2021-04-20 02:24 UTC, seelabs commented
Squashed.

2021-06-04 17:35 UTC, closed without merging