Forward validations and manifests in reporting mode
ripple/rippled pull request #3905
Opened 2021-08-19 01:29 UTC by natenichols

## High Level Overview of Change
Forwards `validations` and `manifest` subscription streams in reporting mode.

### Context of Change
In order for reporting mode to be deployed to s1 and s2, it must support subscriptions to the `validations` and `manifests` streams. 

This PR adds those streams in the same manner as `transactions_proposed`. `validationReceived` and `manifestReceived` messages are forwarded from the ETL Source to subscribers.

### Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

2021-08-19 18:08 UTC, cjcobb23 reviewed
Looks good, did you test this at all?

2021-08-19 18:09 UTC, natenichols commented
Yea, set it up locally and tried out the `validations` stream. Still need to test out the `manifests`

2021-08-19 18:16 UTC, cjcobb23 commented
Can we hook it up to the validations-mainnet bot and make sure everything works correctly?

2021-08-19 18:18 UTC, natenichols commented
Sure, do you have an instance running anywhere? Or should I just set that up locally?

2021-08-19 20:03 UTC, cjcobb23 commented
I don't have an instance; is it a pain to setup locally?

2021-08-19 20:06 UTC, natenichols commented
nah I just might not get to it for a while

2021-08-30 14:07 UTC, cjcobb23 approved these changes
I tested this. Everything looks good.

2021-09-01 19:30 UTC, mtrippled requested changes

2021-09-01 19:30 UTC, mtrippled commented on src/ripple/app/reporting/ETLSource.h
>      /// @param in ETLSource in question
Update the documentation for this function which currently only describes the transaction stream.

2021-09-09 15:53 UTC, mtrippled approved these changes
LGTM :+1:

2021-09-14 16:30 UTC, closed without merging