Log resource limit disconnections.
ripple/rippled pull request #4035
Opened 2021-12-14 17:58 UTC by natenichols

@mtrippled  authored this commit.

## High Level Overview of Change

### Context of Change

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

2021-12-14 21:46 UTC, cjcobb23 approved these changes

2021-12-14 21:47 UTC, cjcobb23 commented
Code looks good but format check failed

2021-12-14 22:32 UTC, thejohnfreeman approved these changes

2021-12-15 17:32 UTC, ximinez requested changes

2021-12-15 17:32 UTC, ximinez commented on src/ripple/resource/impl/Consumer.cpp
> +        JLOG(j.debug()) << "disconnecting " << entry().to_string();
The rest of this function uses `*m_entry`, so using `entry()` here (which is equivalent other than asserting again) seems odd.

2021-12-15 18:14 UTC, ximinez approved these changes
👍

2021-12-17 19:00 UTC, closed without merging